# Generated by Django 3.2.2 on 2021-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiries',
            options={},
        ),
        migrations.AddField(
            model_name='papers',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contacts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='profession',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inquiries',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
    ]
